
#=== BUILD THE BACKEND ===
FROM maven:3.9.9
WORKDIR /app/Backend
COPY LyraBack/pom.xml ./
RUN mvn install -DskipTests
COPY LyraBack/src ./src
COPY ../Docker/entry.sh /entry.sh
RUN chmod +x /entry.sh
EXPOSE 8080
CMD ["/entry.sh" , "backend"]